### ISSUE TITLE
Consider updating `10-service.conf` to call `dbus-update-activation-environment`

### ISSUE THREAD

**Issue by markstos** [xdbob/sway-services#22]
As seen in https://github.com/swaywm/sway/issues/5777 there can be problems launching Flatpaks under Sway due to the dbus environment.

To address this, the Arch Linux package for `sway` ships `/etc/sway/config.d/50-systemd-user.conf`.

To compare, here's the version shipped by this project:

## Current version

```
# Import variables set-up by sway into the environment and notify systemd that
# sway is ready.
exec systemctl --user import-environment SWAYSOCK \
					 DISPLAY \
					 I3SOCK \
					 WAYLAND_DISPLAY \
					 XCURSOR_SIZE \
					 XCURSOR_THEME \
  && systemd-notify --ready
```

## Arch Linux package version:

```
#  sway does not set DISPLAY/WAYLAND_DISPLAY in the systemd user environment
# See FS#63021
# Adapted from xorg's 50-systemd-user.sh, which achieves a similar goal.

exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK
exec hash dbus-update-activation-environment 2>/dev/null && \
     dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK
```

If someone using this project has trouble with Flatpaks, try merging in the approach used by Arch and see it if helps.

**Comment by markstos** [comment]
The sway-systemd project is using the `dbus-update-activation-environment` approach as well:

https://github.com/alebastr/sway-systemd/blob/main/src/session.sh

**Comment by xdbob** [comment]
I am not fond of it, I would recommend users to:

```
include /etc/sway/config.d/*
```
